/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author garci
 */
public class Principal extends javax.swing.JFrame {
 private String mensaje;
 private String prn;

 
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents( );
       // Lba.setText(mensaje);
       
    }
    public void setMensaje(String mensaje){
         Lba2.setText(prn);
    }
  public Principal(String valor2){
             super();// LLAMA AL CONSTRUCTOR DEFAULT DE LA SUPERCLASE
            initComponents();
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   /*public Principal(String valor2){
            super();// LLAMA AL CONSTRUCTOR DEFAULT DE LA SUPERCLASE
            initComponents();
            Mensaje = valor2;
            Lba2.setText (valor2);
      */  }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSegunda = new javax.swing.JButton();
        BtnCerrarPrincipal = new javax.swing.JButton();
        Lba2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSegunda.setText("Ir a Segunda Pantalla");
        BtnSegunda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSegundaMouseClicked(evt);
            }
        });
        BtnSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSegundaActionPerformed(evt);
            }
        });

        BtnCerrarPrincipal.setText("Cerrar");
        BtnCerrarPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarPrincipalMouseClicked(evt);
            }
        });
        BtnCerrarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarPrincipalActionPerformed(evt);
            }
        });

        Lba2.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lba2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSegunda)
                        .addGap(64, 64, 64)
                        .addComponent(BtnCerrarPrincipal)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Lba2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSegunda)
                    .addComponent(BtnCerrarPrincipal))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSegundaActionPerformed
        // TODO add your handling code here:
        String mensaje = "HOLA MUNDO";
        Secundario secu = new Secundario(mensaje, this);
        //secu.setMensaje(mensaje); MANDA EL TEXTO PERO NO LO NECECITAMOS 
        secu.setVisible(true);
       
    }//GEN-LAST:event_BtnSegundaActionPerformed

    private void BtnSegundaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSegundaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSegundaMouseClicked

    private void BtnCerrarPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarPrincipalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarPrincipalMouseClicked

    private void BtnCerrarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarPrincipalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnCerrarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarPrincipal;
    private javax.swing.JButton BtnSegunda;
    private javax.swing.JLabel Lba2;
    // End of variables declaration//GEN-END:variables
}
